name: Build with Gradle

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
          architecture: x64
          check-latest: false
          server-id: github
          server-username: GITHUB_ACTOR
          server-password: GITHUB_TOKEN
          overwrite-settings: true
          job-status: success
          
      - name: Download and set up Gradle
        run: |
          wget https://services.gradle.org/distributions/gradle-7.6.1-bin.zip
          unzip -d $HOME/gradle gradle-7.6.1-bin.zip
          echo "export PATH=\$HOME/gradle/gradle-7.6.1/bin:\$PATH" >> $GITHUB_ENV

      - name: Show Gradle version
        run: gradle --version
      - name: Build with Gradle
        run: gradle build
        
      - name: Store Build Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: src 
